name: Google Compute Engine Create
on:
  workflow_dispatch:
env:
  PROJECT_ID: "bike-path-quality"
  GCE_INSTANCE: "bike-path-quality-analytics"
  GCE_INSTANCE_ZONE: "europe-west2-a"
  GCE_SERVICE_ACCOUNT: "bike-path-quality-analytics@bike-path-quality.iam.gserviceaccount.com"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: "bike-path-quality"
          service_account_key: ${{ secrets.GOOGLE_CLOUD_TOKEN }}
          export_default_credentials: true
        env:
          GOOGLE_CLOUD_TOKEN: ${{ secrets.GOOGLE_CLOUD_TOKEN }}
      - name: Prepare Google Cloud service account token
        id: prepare-google-cloud-service-account-token
        run: echo $GOOGLE_CLOUD_TOKEN | base64 --decode > ./bike-path-quality-2bebc8ae5dc6.json
        env:
          GOOGLE_CLOUD_TOKEN: ${{ secrets.GOOGLE_CLOUD_TOKEN }}
      - name: Create compute instance
        id: create-compute-instance
        run: |
          gcloud compute instances create "$GCE_INSTANCE" \
            --zone="$GCE_INSTANCE_ZONE" \
            --machine-type=n1-standard-8 \
            --image-family=pytorch-latest-gpu \
            --image-project=deeplearning-platform-release \
            --maintenance-policy=TERMINATE \
            --accelerator="type=nvidia-tesla-t4,count=1" \
            --service-account="$GCE_SERVICE_ACCOUNT" \
            --scopes https://www.googleapis.com/auth/cloud-platform \
            --metadata="install-nvidia-driver=True",startup-script='#! /bin/bash
                python -m pip install --upgrade pip
                pip install flake8 pytest
                pip install pandas
                pip install matplotlib
                pip install sklearn
                pip install torch
                pip install tqdm
                pip install seaborn
                pip install telegram-send
                sudo useradd -m -s /bin/bash bike-path-quality-analytics
                sudo -u bike-path-quality-analytics bash -c "mkdir -p ~/.ssh; ssh-keyscan github.com >> ~/.ssh/known_hosts"
                sudo -u bike-path-quality-analytics bash -c "cd ~/; git clone https://github.com/fom-big-data-bike-path-quality/fom-big-data-bike-path-quality-analytics.git"
                sudo -u bike-path-quality-analytics bash -c "cd ~/; git clone https://github.com/fom-big-data-bike-path-quality/fom-big-data-bike-path-quality-data.git fom-big-data-bike-path-quality-analytics/data"
                sudo -u bike-path-quality-analytics bash -c "gsutil cp gs://bike-path-quality-analytics/telegram.config ~/fom-big-data-bike-path-quality-analytics/lib/log/"
                sudo -u bike-path-quality-analytics bash -c "cd ~/fom-big-data-bike-path-quality-analytics; python main.py --epochs=10"
              EOF'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GOOGLE_CLOUD_TOKEN: ${{ secrets.GOOGLE_CLOUD_TOKEN }}