name: Train model (Dry-Run)
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          submodules: recursive
      - name: Prepare Telegram token
        id: prepare-telegram-token
        run: echo $TELEGRAM_TOKEN | base64 --decode > ./lib/telegram.config
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install pandas
          pip install matplotlib
          pip install sklearn
          pip install torch
          pip install tqdm
          pip install seaborn
          pip install telegram-send
          pip install gcloud
          pip install google-api-core
          pip install google-auth
          pip install google-cloud-core
          pip install google-cloud-storage
          pip install dtaidistance
      - name: Run main script with CNN
        id: run-main-script-cnn
        run: |
          python main.py --dry-run --model=cnn
      - name: Run main script with LSTM
        id: run-main-script-lstm
        run: |
          python main.py --dry-run --model=lstm
      - name: Run main script with KNN DTW
        id: run-main-script-knn-dtw
        run: |
          python main.py --dry-run --model=knn-dtw
